# -*- coding: utf-8 -*-
"""data_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VWFZJcC0wyvE9ynHXqwB3HfCyDl4VsJ
"""

import tensorflow as tf

IMAGE_SIZE = (160, 160)
NUM_CLASSES = 4
BATCH_SIZE = 64

def decode_image(file_path, label):
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMAGE_SIZE)
    img = tf.cast(img, tf.float32) / 255.0
    label = tf.one_hot(label, NUM_CLASSES)
    return img, label

def create_datasets(train_paths, val_paths, train_labels, val_labels):
    """Construye y optimiza los pipelines tf.data.Dataset"""
    train_ds = tf.data.Dataset.from_tensor_slices((train_paths, train_labels))
    train_ds = train_ds.shuffle(len(train_paths)).map(decode_image, num_parallel_calls=tf.data.AUTOTUNE)
    train_ds = train_ds.cache().batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

    val_ds = tf.data.Dataset.from_tensor_slices((val_paths, val_labels))
    val_ds = val_ds.map(decode_image, num_parallel_calls=tf.data.AUTOTUNE)
    val_ds = val_ds.cache().batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

    return train_ds, val_ds