# -*- coding: utf-8 -*-
"""models/hybrid_vit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFmHlz-hBefaq0io_1yk70aVgqa9yboA
"""

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2

IMAGE_SIZE = (160, 160)
NUM_CLASSES = 4

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
], name="data_augmentation")

class ViTHead(layers.Layer):
    def __init__(self, embed_dim, num_heads, mlp_dim, num_transformer_layers, dropout_rate=0.1, **kwargs):
        super(ViTHead, self).__init__(**kwargs)
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.mlp_dim = mlp_dim
        self.num_transformer_layers = num_transformer_layers
        self.dropout_rate = dropout_rate

    def build(self, input_shape):
        self.num_patches = input_shape[1] * input_shape[2]
        self.feature_dim = input_shape[3]
        self.projection = layers.Dense(self.embed_dim)
        self.cls_token = self.add_weight(shape=(1, 1, self.embed_dim), initializer="random_normal", trainable=True)
        self.pos_embed = self.add_weight(shape=(1, self.num_patches + 1, self.embed_dim), initializer="random_normal", trainable=True)
        self.transformer_blocks = []
        for _ in range(self.num_transformer_layers):
            self.transformer_blocks.append([
                layers.LayerNormalization(epsilon=1e-6),
                layers.MultiHeadAttention(num_heads=self.num_heads, key_dim=self.embed_dim // self.num_heads, dropout=self.dropout_rate),
                layers.LayerNormalization(epsilon=1e-6),
                layers.Dense(self.mlp_dim, activation="gelu"),
                layers.Dropout(self.dropout_rate),
                layers.Dense(self.embed_dim)
            ])
        self.layer_norm = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs, training=False):
        batch_size = tf.shape(inputs)[0]
        x = tf.reshape(inputs, [batch_size, self.num_patches, self.feature_dim])
        x = self.projection(x)
        cls_tokens = tf.broadcast_to(self.cls_token, [batch_size, 1, self.embed_dim])
        x = tf.concat([cls_tokens, x], axis=1)
        x = x + self.pos_embed
        for norm1, attn, norm2, dense1, drop1, dense2 in self.transformer_blocks:
            x_norm = norm1(x)
            x = x + attn(x_norm, x_norm, x_norm, training=training)
            x_norm = norm2(x)
            x = x + dense2(drop1(dense1(x_norm), training=training))
        return self.layer_norm(x)[:, 0]

def build_experiment_model(use_vit=True, use_augmentation=False, vit_config=None):
    inputs = layers.Input(shape=(*IMAGE_SIZE, 3))
    x = inputs

    if use_augmentation:
        x = data_augmentation(x)

    base_model = MobileNetV2(include_top=False, weights="imagenet", input_shape=(*IMAGE_SIZE, 3))

    layer_n = len(base_model.layers)
    freeze = int(layer_n * 0.9)
    for i, layer in enumerate(base_model.layers):
        layer.trainable = (i >= freeze)

    x = base_model(x, training=False)

    if use_vit:
        cfg = vit_config if vit_config else {'embed_dim': 256, 'num_heads': 4, 'mlp_dim': 512, 'layers': 2}
        x = ViTHead(
            embed_dim=cfg['embed_dim'],
            num_heads=cfg['num_heads'],
            mlp_dim=cfg['mlp_dim'],
            num_transformer_layers=cfg['layers']
        )(x)
    else:
        # Solo CNN
        x = layers.GlobalAveragePooling2D()(x)
        x = layers.Dense(256, activation='relu')(x)

    x = layers.Dropout(0.5)(x)
    outputs = layers.Dense(NUM_CLASSES, activation='softmax')(x)

    model = models.Model(inputs, outputs)
    return model, base_model, freeze